### ISSUE TITLE
No tensorflow in the aizynthtrain environment

### ISSUE THREAD

**Issue by JeremyMolineau** [MolecularAI/aizynthtrain#13]
Hello,
I'm running the last part to train the model (step 5. in USAGE)
It seems that "tensorflow" is missing from the environment after installing with poetry.

![git_tensorflow](https://github.com/MolecularAI/aizynthtrain/assets/113370060/7cbd0ad7-9d59-415e-98de-54f8f1a06df6)

**Comment by SGenheden** [comment]
I thought we fixed this, but apparently not.

Can you try to type this in your environement:

```
python -m pip install aizynthfinder[all,tf]
```

and see if this works

**Comment by JeremyMolineau** [comment]
It works. Tensorflow is now in my environment. 
Thank you

**Comment by SGenheden** [comment]
Tensorflow has now been added to the pyproject.toml
