### ISSUE TITLE
PapermillExecutionError at line 29 in reporting.py

### ISSUE THREAD

**Issue by mujeebarshad** [MolecularAI/aizynthtrain#18]
![image](https://github.com/MolecularAI/aizynthtrain/assets/29289499/b9d063ed-a744-4bdf-b5ae-6a0c2b03567c)

Generated `uspto_mapped.csv` and now Facing this error when running script `template_pipeline.sh`. After some hours `validated_reactions.csv` has been created but then get the error in the screenshot.
Any idea how to resolve it? Already tried the installing the papermill from git as mentioned in one of the issue as a solution using following commands.

`conda activate aizynthtrain
python -m pip uninstall papermill
python -m pip install git+https://github.com/nteract/papermill.git`

**Comment by SGenheden** [comment]
This might be related to #17 
I suggest you checkout the solution in that issue and report back on this issue.

**Comment by SGenheden** [comment]
Closing this. Let me know if #19 did not solve it.
