### ISSUE TITLE
Help with aizynthtrain

### ISSUE THREAD

**Issue by SBandC** [MolecularAI/aizynthtrain#8]
Hi,

I'd like to train a model from new data and first I try to follow your documentation and try to reproduce math is done with uspto data.
I succeeded in creating different environments :
aizhynthfinder-env
rnx-env
rxnmapper
I'm able to run the two pipelines preparation_pipeline (from rxn-env) and mapping_pipeline (from rnxmapper) and to obtain the two files : uspto_data_cleaned.csv and uspto_data_mapped.csv
But I have some troubles  with aizynthtrain.
By activativing rxn-env I'm able to access to the right python from the rnx-env environment and to the mapping_pipeline.py that is in a different folder (the one from the clone of the git repo).
When I activate aizynthtrain environment the python used is well the one from the environment but I'm faced to that error : path_to_aizynthtrain/bin/python: Error while finding module specification for 'aizynthtrain.pipelines.template_pipeline' (ModuleNotFoundError: No module named 'aizynthtrain'). Python is unable to access to the code from the git clone of aizynthtrain.
I'd like to add that I'm trying to run the commands below extracted from the template_pipeline.sh to test on my machine before to try it on a cluster :
conda activate path_to_aizynthtrain/aizynthtrain
python -m aizynthtrain.pipelines.template_pipeline run --config template_pipeline_config.yml --max-workers 8 --max-num-splits 200

I have just encountered a problem during the setting of aizynthtrain environment : 
Installing sklearn (0.0.post1): Failed
But scikit-learn is present in the environment and I was able to test it positively.

Any help would be really appreciated.
Thanks

**Comment by SGenheden** [comment]
Hello
It looks like aizynthtrain was never installed in the `aizynthtrain` environment. Can you double check by
1. Goto the folder of the `aizynthtrain` Git repo
2. Activate the conda environment
3. Execute `poetry install`
if you had some issue with the poetry execution, it might be that it never completed the installation of `aizynthtrain`.

**Comment by SBandC** [comment]
Hello.

Thanks for the answer.
You probably find what's wrong.  When I list (conda list) the packages installed in the aizynthtrain environment I can't find aizynthtrain, but aizynthfinder is installed (version) 3.4.0.
I have a problem following the poetry install command, a problem regarding sklearn. I rerun poetry install and obtain this time only the error message :
Installing dependencies from lock file

Package operations: 1 install, 0 updates, 0 removals

  • Installing sklearn (0.0.post1): Failed

  ChefBuildError

  Backend subprocess exited when trying to invoke get_requires_for_build_wheel
  
  The 'sklearn' PyPI package is deprecated, use 'scikit-learn'
  rather than 'sklearn' for pip commands. 
  
  Here is how to fix this error in the main use cases:
  - use 'pip install scikit-learn' rather than 'pip install sklearn'
  - replace 'sklearn' by 'scikit-learn' in your pip requirements files
    (requirements.txt, setup.py, setup.cfg, Pipfile, etc ...)
  - if the 'sklearn' package is used by one of your dependencies,
    it would be great if you take some time to track which package uses
    'sklearn' instead of 'scikit-learn' and report it to their issue tracker
  - as a last resort, set the environment variable
    SKLEARN_ALLOW_DEPRECATED_SKLEARN_PACKAGE_INSTALL=True to avoid this error
  
  More information is available at
  https://github.com/scikit-learn/sklearn-pypi-package
  
  If the previous advice does not cover your use case, feel free to report it at
  https://github.com/scikit-learn/sklearn-pypi-package/issues/new
  

  at /media/bourg@ICOA-03.LOCAL/Data/Recherche/CEA/aizynthtrain/lib/python3.9/site-packages/poetry/installation/chef.py:164 in _prepare
      160│ 
      161│                 error = ChefBuildError("\n\n".join(message_parts))
      162│ 
      163│             if error is not None:
    → 164│                 raise error from None
      165│ 
      166│             return path
      167│ 
      168│     def _prepare_sdist(self, archive: Path, destination: Path | None = None) -> Path:

Note: This error originates from the build backend, and is likely not a problem with poetry but with sklearn (0.0.post1) not supporting PEP 517 builds. You can verify this by running 'pip wheel --no-cache-dir --use-pep517 "sklearn (==0.0.post1)"'.

I'm surprised because scikit-learn (1.2.2 from pypi) is installed and I have tested the library which is ok.

I'm not familiar with poetry. So It seems the installation process is not completed.

What should I do to correct the sklearn error  and continue the installation ?

**Comment by SGenheden** [comment]
The dependencies are a bit old. I have pushed a branch where I have updated the dependencies.
Please try this
```
git checkout update-dependencies
poetry install
```

if poetry still complaints. Try to remove the conda environment, create it again and then install with poetry.

**Comment by JeremyMolineau** [comment]
Thank you for your responses. 
We have tested it with @SBC-ICOA 
Problems have been fixed with updated dependencies.
