### ISSUE TITLE
template extraction issue

### ISSUE THREAD

**Issue by steveowk** [MolecularAI/aizynthtrain#9]
Hi,
Seeking help with an issue on template extraction (step 4).
A key seems to be missing from a dict. (see the attached)
![error](https://github.com/MolecularAI/aizynthtrain/assets/13416443/6b3a3d94-03f4-446a-b8c2-95be22842e96)

Been able to generate the uspto  mapped csv successfully.

Thanks.

**Comment by SGenheden** [comment]
Hello.
This action, the "hasunmappedradicalatom" was introduce in rxnutils 1.2. 
Could it be that you have an old version rxnutils installed in your environment?
Could try to do "pip install -U reaction-utils"?

**Comment by steveowk** [comment]
Hello

Thanks for the response.
After the update, the error is not there. 
However, the template extraction pipeline still fails (while executing template_pipeline.sh)

![error2](https://github.com/MolecularAI/aizynthtrain/assets/13416443/f83da181-5cce-416f-89ee-552a0aa223e5)

**Comment by SGenheden** [comment]
Did you install a Jupyter kernel?
`ipython kernel install --name "aizynthtrain" --user`

**Comment by steveowk** [comment]
Hello

Yes. 

I have rerun the train env set-up but have the same error.

**Comment by SGenheden** [comment]
I find this very peculiar. 
We just pushed a new version. Could you try and re-install (or at least git pull + poetry update)?

**Comment by JeremyMolineau** [comment]
Hello,
I'm having the same problem with kernelspec. 
After following your suggestions (git pull & poetry update), no improvement.
I tried to specify the python_kernel in aizynthtrain/utils/configs.py in class TemplatePipelineConfig(BaseModel):  like this  python_kernel: str = "aizynthtrain"    --> no improvement.

A check with the command (jupyter kernelspec list) showed me that the kernel exists. 
output = aizynthtrain       /home/.local/share/jupyter/kernels/aizynthtrain

**Comment by SGenheden** [comment]
Hello.
We encountered the same issue with our internal setup, and we found a solution. It is not elegant but it works for now
The thing is that is requires a new feature in the `papermill` package that has not been released, but this worked for us

```
conda activate aizynthtrain
python -m pip uninstall papermill
python -m pip install git+https://github.com/nteract/papermill.git
```

**Comment by JeremyMolineau** [comment]
Thank you, this problem is solved on my side.
